//기본 조회 데이터 정제

//1. 날짜 확인해서 데이터 업데이트 해주고 갖고 있는 데이터(알람이 꺼졌는지 켜졌는지)랑 
//새로 가져온 데이터(일정이 추가되거나 옵션이 변경된 경우)랑 비교해서 업데이트 해줌.
//(왜? 알림이 작동했는지 여부를 체크해야 하기 때문에)
//





//기본 조회 데이터
//(GET) http://localhost:8080/api/todo/alarm/todolist
//@param : userIdx, number
//@param : todoDate, yyyy-mm-dd
const sampleData = [
  {
      "todoIdx": 125,
      "userIdx": 32,
      "todoContents": "에브리 화요일",
      "todoDate": "2023-10-03 01:18:20",
      "todoDone": 0,
      "todoDelete": "N",
      "todoStartDate": "2023-10-03",
      "todoEndDate": "2023-10-03",
      "todoDoneDate": null,
      "todoAlarm": 1,
      "todoAlarmTime": "2023-10-03 04:10:00",
      "userEmail": null,
      "todoPoint": 100,
      "todoMon": 0,
      "todoTue": 1,
      "todoWed": 0,
      "todoThu": 0,
      "todoFri": 0,
      "todoSat": 0,
      "todoSun": 0,
      "todoDoneIdx": 67,
      "todoDoneCheck": 0,
      "todoDoneTime": null
  },
  {
      "todoIdx": 126,
      "userIdx": 32,
      "todoContents": "수요일",
      "todoDate": "2023-10-03 01:19:00",
      "todoDone": 0,
      "todoDelete": "N",
      "todoStartDate": "2023-10-04",
      "todoEndDate": "2023-10-04",
      "todoDoneDate": null,
      "todoAlarm": 1,
      "todoAlarmTime": "2023-10-04 01:00:00",
      "userEmail": null,
      "todoPoint": 100,
      "todoMon": 0,
      "todoTue": 0,
      "todoWed": 0,
      "todoThu": 0,
      "todoFri": 0,
      "todoSat": 0,
      "todoSun": 0,
      "todoDoneIdx": 0,
      "todoDoneCheck": 0,
      "todoDoneTime": null
  },
  {
      "todoIdx": 127,
      "userIdx": 32,
      "todoContents": "매주 목,금,토",
      "todoDate": "2023-10-05 00:34:40",
      "todoDone": 0,
      "todoDelete": "N",
      "todoStartDate": "2023-10-05",
      "todoEndDate": "2023-10-05",
      "todoDoneDate": null,
      "todoAlarm": 1,
      "todoAlarmTime": "2023-10-05 01:05:00",
      "userEmail": null,
      "todoPoint": 100,
      "todoMon": 0,
      "todoTue": 0,
      "todoWed": 0,
      "todoThu": 1,
      "todoFri": 1,
      "todoSat": 1,
      "todoSun": 0,
      "todoDoneIdx": 0,
      "todoDoneCheck": 0,
      "todoDoneTime": null
  },
  {
      "todoIdx": 128,
      "userIdx": 32,
      "todoContents": "today일요일",
      "todoDate": "2023-10-08 00:50:16",
      "todoDone": 0,
      "todoDelete": "N",
      "todoStartDate": "2023-10-08",
      "todoEndDate": "2023-10-08",
      "todoDoneDate": null,
      "todoAlarm": 1,
      "todoAlarmTime": "2023-10-08 02:00:00",
      "userEmail": null,
      "todoPoint": 100,
      "todoMon": 0,
      "todoTue": 0,
      "todoWed": 0,
      "todoThu": 0,
      "todoFri": 0,
      "todoSat": 0,
      "todoSun": 0,
      "todoDoneIdx": 0,
      "todoDoneCheck": 0,
      "todoDoneTime": null
  },
  {
      "todoIdx": 129,
      "userIdx": 32,
      "todoContents": "알람 설정",
      "todoDate": "2023-11-12 23:19:48",
      "todoDone": 0,
      "todoDelete": "N",
      "todoStartDate": "2023-11-12",
      "todoEndDate": "2023-11-12",
      "todoDoneDate": null,
      "todoAlarm": 1,
      "todoAlarmTime": "2023-11-12 01:05:00",
      "userEmail": null,
      "todoPoint": 100,
      "todoMon": 0,
      "todoTue": 0,
      "todoWed": 0,
      "todoThu": 0,
      "todoFri": 0,
      "todoSat": 0,
      "todoSun": 0,
      "todoDoneIdx": 0,
      "todoDoneCheck": 0,
      "todoDoneTime": null
  },
  {
      "todoIdx": 130,
      "userIdx": 32,
      "todoContents": "매주 월요일 알람 설정",
      "todoDate": "2023-11-12 23:20:12",
      "todoDone": 0,
      "todoDelete": "N",
      "todoStartDate": "2023-11-13",
      "todoEndDate": null,
      "todoDoneDate": null,
      "todoAlarm": 1,
      "todoAlarmTime": "2023-11-13 02:00:00",
      "userEmail": null,
      "todoPoint": 200,
      "todoMon": 1,
      "todoTue": 0,
      "todoWed": 0,
      "todoThu": 0,
      "todoFri": 0,
      "todoSat": 0,
      "todoSun": 0,
      "todoDoneIdx": 0,
      "todoDoneCheck": 0,
      "todoDoneTime": null
  }
]